"""
=============================================================================
DATA VISUALIZATION: MIS Geographic Map (Prado Velho)
=============================================================================
Reads the physical coordinates from the IPPUC dataset and the latest optimal 
configuration generated by the quantum/hybrid algorithm. 
It plots a geographical map showing:
- Grey dots: Streetlights turned OFF (to save energy / avoid overlap)
- Yellow dots: Streetlights turned ON
- Transparent Yellow Circles: The physical illumination radius (LED cone)

This visually proves that the Maximal Independent Set (MIS) constraint works,
as the light cones should not intersect.
=============================================================================
"""

import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def get_latest_config_file(results_dir):
    """Finds the most recently generated optimal config .txt file."""
    search_pattern = os.path.join(results_dir, "*_optimal_config_*.txt")
    files = glob.glob(search_pattern)
    if not files:
        return None
    # Sort files by modification time (latest first)
    files.sort(key=os.path.getmtime, reverse=True)
    return files[0]

def parse_config_txt(filepath):
    """Reads the .txt file and extracts the 1s and 0s array."""
    with open(filepath, 'r') as file:
        lines = file.readlines()
    
    # The LED configuration is always printed on the last line of our TXT
    config_line = lines[-1].strip().split()
    return [int(val) for val in config_line]

def plot_geographic_mis(led_radius_meters=20.0):
    # 1. Setup paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.dirname(script_dir)
    data_path = os.path.join(src_dir, "data", "paranainterativo.csv")
    results_dir = os.path.join(src_dir, "results")
    
    # 2. Get the latest configuration
    latest_txt = get_latest_config_file(results_dir)
    if not latest_txt:
        print("[ERROR] No optimal configuration .txt found in the results folder.")
        print("Please run lattice_network_evolution.py first.")
        return
        
    print(f"-> Reading configuration from: {os.path.basename(latest_txt)}")
    led_states = parse_config_txt(latest_txt)
    n_streetlights = len(led_states)
    
    # 3. Read the geographic data
    try:
        df = pd.read_csv(data_path).head(n_streetlights)
    except FileNotFoundError:
        print(f"[ERROR] Could not find the CSV data at {data_path}")
        return

    # 4. Math for geographic projection (converting meters to degrees for the plot)
    mean_lat = df['latitude'].mean()
    meters_per_degree = 111320.0
    radius_in_degrees = led_radius_meters / meters_per_degree

    # 5. Plotting
    fig, ax = plt.subplots(figsize=(12, 10))
    
    # Aspect ratio adjustment is crucial so the circles don't look like flattened ovals
    # because of the Earth's curvature at Curitiba's latitude.
    ax.set_aspect(1 / np.cos(np.radians(mean_lat)))
    ax.set_title(f"Quantum Optimization: MIS Energy Efficiency Map\n{n_streetlights} Streetlights | Radius: {led_radius_meters}m", 
                 fontsize=14, fontweight='bold', pad=15)
    
    on_count = 0
    
    for i, row in df.iterrows():
        lon = row['longitude']
        lat = row['latitude']
        state = led_states[i]
        
        if state == 1:
            on_count += 1
            # Plot the LED pole
            ax.scatter(lon, lat, color='gold', s=40, zorder=3, edgecolors='black')
            # Draw the Light Radius
            light_cone = plt.Circle((lon, lat), radius_in_degrees, color='yellow', alpha=0.3, zorder=2)
            ax.add_patch(light_cone)
        else:
            # Plot turned off poles
            ax.scatter(lon, lat, color='grey', s=15, zorder=3, alpha=0.6)

    plt.xlabel('Longitude', fontsize=11, fontweight='bold')
    plt.ylabel('Latitude', fontsize=11, fontweight='bold')
    plt.grid(True, linestyle='--', alpha=0.4)
    
    # Custom Legend
    from matplotlib.lines import Line2D
    legend_elements = [
        Line2D([0], [0], marker='o', color='w', label=f'ON ({on_count} LEDs)', markerfacecolor='gold', markersize=10, markeredgecolor='black'),
        Line2D([0], [0], marker='o', color='w', label=f'OFF ({n_streetlights - on_count} LEDs)', markerfacecolor='grey', markersize=8),
    ]
    ax.legend(handles=legend_elements, loc='upper right', fontsize=11)

    plt.tight_layout()
    
    # Save output dynamically reflecting the radius size in the filename
    radius_str = str(int(led_radius_meters)) if led_radius_meters.is_integer() else str(led_radius_meters)
    output_filename = os.path.join(results_dir, f"mis_geographic_map_{radius_str}m.png")
    plt.savefig(output_filename, dpi=300)
    print(f"-> Energy savings: {n_streetlights - on_count} streetlights turned off.")
    print(f"-> Map successfully generated and saved to: {output_filename}")
    
    plt.show()

if __name__ == "__main__":
    # Ensure this matches the radius used in real_graph_qubo.py
    plot_geographic_mis(led_radius_meters=20.0)