"""
=============================================================================
DATA VISUALIZATION: Convergence Analysis (5 Algorithms)
=============================================================================
Reads the CSV reports generated by the evolutionary engine and plots the 
energy convergence curve for Hill Climbing, Simulated Annealing, Gradient 
Descent, Genetic Algorithm, and Differential Evolution.
=============================================================================
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
import glob

def get_latest_file(directory, pattern):
    search_path = os.path.join(directory, pattern)
    files = glob.glob(search_path)
    if not files:
        return None
    files.sort(key=os.path.getmtime, reverse=True)
    return files[0]

def plot_algorithmic_convergence(paths_dict, output_filename="convergence_analysis.png"):
    print("\n--- Generating Convergence Chart ---")
    
    # Figure configuration (size and style)
    plt.figure(figsize=(12, 7))
    plt.title("Quantum Optimization: Algorithmic Convergence Comparison", fontsize=14, fontweight='bold', pad=15)
    
    # Style dictionary for each algorithm
    styles = {
        'HC': {'label': 'Hill Climbing (Greedy)', 'color': '#1f77b4', 'ls': '-'},
        'SA': {'label': 'Simulated Annealing (Thermal)', 'color': '#ff7f0e', 'ls': '-'},
        'GD': {'label': 'Gradient Descent (Math)', 'color': '#2ca02c', 'ls': '--'},
        'GA': {'label': 'Genetic Algorithm (Bio)', 'color': '#d62728', 'ls': ':'},
        'DE': {'label': 'Differential Evolution (Algebraic)', 'color': '#9467bd', 'ls': '-.'}
    }
    
    data_found = False

    # Plot each algorithm found in the dictionary
    for alg_key, csv_path in paths_dict.items():
        if csv_path and os.path.exists(csv_path):
            print(f"Reading {alg_key} data: {os.path.basename(csv_path)}")
            try:
                df = pd.read_csv(csv_path)
                plt.plot(df['generation'], df['objective_cx'], 
                         label=styles[alg_key]['label'], 
                         color=styles[alg_key]['color'], 
                         linewidth=2.0, 
                         linestyle=styles[alg_key]['ls'], 
                         alpha=0.85)
                data_found = True
            except Exception as e:
                print(f"[ERROR] Could not read {alg_key}: {e}")
        else:
            print(f"[WARNING] No data found for {alg_key}. Skipping...")

    if not data_found:
        print("\n[ERROR] No valid CSV files found to plot. Aborting.")
        return

    # Formatting axes
    plt.xlabel('Generation (Iterations)', fontsize=12, fontweight='bold')
    plt.ylabel('Equivalent Classical Cost - C(x)', fontsize=12, fontweight='bold')
    
    # Adding a grid for readability
    plt.grid(True, linestyle='--', alpha=0.6)
    
    # Legend
    plt.legend(fontsize=11, loc='upper right', framealpha=1.0)
    
    # Adjusting layout margins
    plt.tight_layout()
    
    # ---------------------------------------------------------
    # DATA PERSISTENCE
    # ---------------------------------------------------------
    current_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = current_dir
    while not os.path.exists(os.path.join(src_dir, "data")):
        src_dir = os.path.dirname(src_dir)
        
    results_dir = os.path.join(src_dir, "results")
    output_path = os.path.join(results_dir, output_filename)
    
    plt.savefig(output_path, dpi=300) 
    print(f"\n-> Chart successfully generated and saved to: {output_path}")
    
    plt.show()

if __name__ == "__main__":
    current_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = current_dir
    while not os.path.exists(os.path.join(src_dir, "data")):
        src_dir = os.path.dirname(src_dir)
        
    results_dir = os.path.join(src_dir, "results")
    
    patterns = {
        'HC': "*_leds_hc_history_*.csv",
        'SA': "*_leds_sa_history_*.csv",
        'GD': "*_leds_gd_history_*.csv",
        'GA': "*_leds_ga_history_*.csv",
        'DE': "*_leds_de_history_*.csv"
    }
    
    paths_dict = {alg: get_latest_file(results_dir, pat) for alg, pat in patterns.items()}
    
    plot_algorithmic_convergence(paths_dict)