"""
=============================================================================
DATA VISUALIZATION: Convergence Analysis
=============================================================================
Reads the CSV reports generated by the evolutionary engine and plots the 
energy convergence curve. Allows for a visual comparison between the greedy 
behavior of Hill Climbing and the thermal fluctuations of Simulated Annealing.
=============================================================================
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

def plot_algorithmic_convergence(hc_csv_path: str, sa_csv_path: str, output_filename: str = "convergence_analysis.png"):
    print(f"Reading Hill Climbing data: {os.path.basename(hc_csv_path)}")
    print(f"Reading Simulated Annealing data: {os.path.basename(sa_csv_path)}")

    try:
        df_hc = pd.read_csv(hc_csv_path)
        df_sa = pd.read_csv(sa_csv_path)
    except FileNotFoundError as e:
        print(f"\n[ERROR] File not found: {e}")
        print("Please check if the filenames in the main block match your generated results.")
        return

    # Figure configuration (size and style)
    plt.figure(figsize=(10, 6))
    plt.title("Quantum Optimization: Hill Climbing vs Simulated Annealing", fontsize=14, fontweight='bold', pad=15)
    
    # Plotting the Hill Climbing line (Blue, thicker)
    plt.plot(df_hc['generation'], df_hc['objective_cx'], 
             label='Hill Climbing (Greedy)', 
             color='#1f77b4', linewidth=2.5, linestyle='-')
    
    # Plotting the Simulated Annealing line (Orange, slightly transparent)
    plt.plot(df_sa['generation'], df_sa['objective_cx'], 
             label='Simulated Annealing (Thermal)', 
             color='#ff7f0e', linewidth=2.0, alpha=0.85)
    
    # Formatting axes
    plt.xlabel('Generation (Iterations)', fontsize=12, fontweight='bold')
    plt.ylabel('Equivalent Classical Cost - C(x)', fontsize=12, fontweight='bold')
    
    # Adding a grid for readability
    plt.grid(True, linestyle='--', alpha=0.6)
    
    # Legend
    plt.legend(fontsize=11, loc='upper right', framealpha=1.0)
    
    # Adjusting layout margins
    plt.tight_layout()
    
    # Saving the image to the results directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    base_dir = os.path.dirname(script_dir) 
    results_dir = os.path.join(base_dir, "results")
    output_path = os.path.join(results_dir, output_filename)
    
    plt.savefig(output_path, dpi=300) # High resolution for the report
    print(f"\n-> Chart successfully generated and saved to: {output_path}")
    
    # Displaying the chart on screen
    plt.show()

if __name__ == "__main__":
    # Getting the current script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    base_dir = os.path.dirname(script_dir)
    
    # =========================================================================
    # ATTENTION: Replace the filenames below with the exact files generated
    # during your tests (check your terminal history or results folder).
    # =========================================================================
    ARQUIVO_HC = "prado_velho_3_leds_history_20260727_130518.csv"
    ARQUIVO_SA = "prado_velho_3_leds_sa_history_20260727_130525.csv"
    
    caminho_hc = os.path.join(base_dir, "results", ARQUIVO_HC)
    caminho_sa = os.path.join(base_dir, "results", ARQUIVO_SA)
    
    plot_algorithmic_convergence(caminho_hc, caminho_sa)