"""
=============================================================================
DATA VISUALIZATION: Convergence Analysis
=============================================================================
Reads the CSV reports generated by the evolutionary engine and plots the 
energy convergence curve. Allows for a visual comparison between the greedy 
behavior of Hill Climbing and the thermal fluctuations of Simulated Annealing.
=============================================================================
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
import glob

def get_latest_file(directory, pattern):
    search_path = os.path.join(directory, pattern)
    files = glob.glob(search_path)
    if not files:
        return None
    files.sort(key=os.path.getmtime, reverse=True)
    return files[0]

def plot_algorithmic_convergence(hc_csv_path: str, sa_csv_path: str, output_filename: str = "convergence_analysis.png"):
    print(f"Reading Hill Climbing data: {os.path.basename(hc_csv_path)}")
    print(f"Reading Simulated Annealing data: {os.path.basename(sa_csv_path)}")

    try:
        df_hc = pd.read_csv(hc_csv_path)
        df_sa = pd.read_csv(sa_csv_path)
    except FileNotFoundError as e:
        print(f"\n[ERROR] File not found: {e}")
        print("Please check if the filenames in the main block match your generated results.")
        return

    # Figure configuration (size and style)
    plt.figure(figsize=(10, 6))
    plt.title("Quantum Optimization: Hill Climbing vs Simulated Annealing", fontsize=14, fontweight='bold', pad=15)
    
    # Plotting the Hill Climbing line (Blue, thicker)
    plt.plot(df_hc['generation'], df_hc['objective_cx'], 
             label='Hill Climbing (Greedy)', 
             color='#1f77b4', linewidth=2.5, linestyle='-')
    
    # Plotting the Simulated Annealing line (Orange, slightly transparent)
    plt.plot(df_sa['generation'], df_sa['objective_cx'], 
             label='Simulated Annealing (Thermal)', 
             color='#ff7f0e', linewidth=2.0, alpha=0.85)
    
    # Formatting axes
    plt.xlabel('Generation (Iterations)', fontsize=12, fontweight='bold')
    plt.ylabel('Equivalent Classical Cost - C(x)', fontsize=12, fontweight='bold')
    
    # Adding a grid for readability
    plt.grid(True, linestyle='--', alpha=0.6)
    
    # Legend
    plt.legend(fontsize=11, loc='upper right', framealpha=1.0)
    
    # Adjusting layout margins
    plt.tight_layout()
    
    # Saving the image to the results directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    base_dir = os.path.dirname(script_dir) 
    results_dir = os.path.join(base_dir, "results")
    output_path = os.path.join(results_dir, output_filename)
    
    plt.savefig(output_path, dpi=300) # High resolution for the report
    print(f"\n-> Chart successfully generated and saved to: {output_path}")
    
    # Displaying the chart on screen
    plt.show()

if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    base_dir = os.path.dirname(script_dir) 
    results_dir = os.path.join(base_dir, "results")
    
    hc_pattern = "*_leds_history_*.csv"
    sa_pattern = "*_leds_sa_history_*.csv"
    
    path_hc = get_latest_file(results_dir, hc_pattern)
    path_sa = get_latest_file(results_dir, sa_pattern)
    
    if not path_hc or not path_sa:
        print("\n[ERROR] Could not find the CSV files in the 'results/' folder.")
        print("Make sure to run 'lattice_network_evolution.py' first.")
    else:
        plot_algorithmic_convergence(path_hc, path_sa)